spring.application.name=GenreDive

# Datasource and its configs

spring.datasource.url=jdbc:postgresql://localhost:5432/GenreDive
spring.datasource.username= user
spring.datasource.password=Servidor123
spring.datasource.driver-class-name=org.postgresql.Driver
